def custom_exception():
    pass  # TODO
